const globalMsg = {

  common: {
    CREATED_SUCCESSFULLY: "CREATED_SUCCESSFULLY",
    FETCH_DATA_SUCCESSFULLY: "FETCH_DATA_SUCCESSFULLY",
    UPDATED_SUCCESSFULLY: "UPDATED_SUCCESSFULL",
    DELTED_SUCESSFULLY: "DELTED_SUCESSFULLY",
    COUNTRY_LIST: "COUNTRY_LIST",
    STATE_LIST: "STATE_LIST",
    CURRENCY_LIST: "CURRENCY_LIST",
  },

  errors: {

    AGENCY_ALREADY_EXIST: "AGENCY_ALREADY_EXIST",
    NO_AGENCY_FOUND: "NO_AGENCY_FOUND",
    AGENCY_TARIFF_PACKAGE_ALREADY_EXIST: "AGENCY_TARIFF_PACKAGE_ALREADY_EXIST",
    NO_TARIFF_PACKAGE_FOUND: "NO_TARIFF_PACKAGE_FOUND",
    NO_AGENCY_VEHICLE_FOUND: "NO_AGENCY_VEHICLE_FOUND",
    NO_CUSTOMER_QUOTATION_EXISTING: "NO_CUSTOMER_QUOTATION_EXISTING",
    NO_DATA_FOUND: "NO_DATA_FOUND",
    INVALID_OTP: "INVALID_OTP",
    NO_USER_DATA_FOUND: "NO_USER-DATA_FOUND",
    NO_USER_EXITST: "NO_USER_EXITST",
    NO_CUSTOMER_FOUND: "NO_CUSTOMER_FOUND",
    NO_ORG_BOOKING_EXIST: "NO_ORG_BOOKING_EXIST",
    COMPANY_COULD_NOT_BE_REGISTERED: "COMPANY_COULD_NOT_BE_REGISTERED",
    USER_COULD_NOT_BE_REGISTERED: "USER_COULD_NOT_BE_REGISTERED",
    NO_ORGANIZATION_FOUND: "NO_ORGANIZATION_FOUND",
    ORGANIZATION_ALREADY_EXIST: "ORGANIZATION_ALREADY_EXIST",
    SUBSCRIPTION_PLAN_ALREADY_EXIST: "SUBSCRIPTION_PLAN_ALREADY_EXIST",
    NO_SUBSCRIPTION_PLAN_FOUND: "NO_SUBSCRIPTION_PLAN_FOUND",

    NO_VEHICLEBRAND_EXIST: "NO_VEHICLEBRAND_EXIST",
    VEHICLEBRAND_ALREADY_EXIST: "VEHICLEBRAND_ALREADY_EXIST",
    VEHICLE_CATEGORY_ALREADY_EXIST: "VEHICLE_CATEGORY_ALREADY_EXIST",
    VEHICLE_CATEGORY_NOT_EXIST: "VEHICLE_CATEGORY_NOT_EXIST",
    VEHICLE_TYPE_NOT_EXIST: "VEHICLE_TYPE_NOT_EXIST",
    VEHICLE_TYPE_ALREADY_EXIST: "VEHICLE_TYPE_ALREADY_EXIST",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    REQUEST_DATA_REQUIRED: "REQUEST_DATA_REQUIRED"
  },

  auth: {
    LOGGED_IN_SUCCESSFUL: "LOGGED_IN_SUCCESSFUL",
    PASSWORD_UPDATED_SUCCESS: "PASSWORD_UPDATED_SUCCESS",
    REGISTERED_SUCCESSFULLY: "REGISTERED_SUCCESSFULLY",
    REGISTERED_TO_ORGANIZATION_SUCCESSFULLY: "REGISTERED_TO_ORGANIZATION_SUCCESSFULLY",
    CURRENT_LOGGEDIN_USER: "CURRENT_LOGGEDIN_USER",
    PASSWORD_UPDATED_SUCCESSFULLY: "PASSWORD_UPDATED_SUCCESSFULLY",

    // error messages for auth
    ERROR_SENDING_EMAIL: "ERROR_SENDING_EMAIL",
    ERROR_SENDING_MAIL: "ERROR_SENDING_MAIL",
    COULD_NOT_ASSIGN_ROLE: "COULD_NOT_ASSIGN_ROLE",
    PASSWORD_DOES_NOT_MATCH: "PASSWORD_DOES_NOT_MATCH",
    NO_CUSTOMER_FOUND: "NO_CUSTOMER_FOUND",
    COULD_NOT_UPDATE_PASSWORD: "COULD_NOT_UPDATE_PASSWORD",
    OTP_VERIFICATION_FAILED: "OTP_VERIFICATION_FAILED",
    USER_ALREADY_REGISTERED: "USER_ALREADY_REGISTERED",
    PASSWORD_COULD_NOT_BE_UPDATED: "PASSWORD_COULD_NOT_BE_UPDATED",
    INACTIVE_ACCOUNT: "INACTIVE_ACCOUNT",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  },

  CREATE_AGENCY_SUCCESS: "CREATE_AGENCY_SUCCESS",

  FIND_ALL_AGENCY_SUCCESS: "FIND_ALL_AGENCY_SUCCESS",
  UPDATE_AGENCY_SUCCESS: "UPDATE_AGENCY_SUCCESS",
  FIND_AGENCY_SUCCESS: "FIND_AGENCY_SUCCESS",

  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_ORG_SUCCESS: "UPDATE_ORG_SUCCESS",
  VEHICLE_TYPE_UPDATE_SUCCESS: "VEHICLE_TYPE_UPDATE_SUCCESS",
  UPDATE_VEHICLE_CATEGORY_SUCCESS: "UPDATE_VEHICLE_CATEGORY_SUCCESS",
  UPDATE_VEHICLEBRAND_SUCCESS: "UPDATE_VEHICLEBRAND_SUCCESS",
  UPDATE_AGENCY_VEHICLE_SUCCESS: "UPDATE_AGENCY_VEHICLE_SUCCESS",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_ORG_SUCCESS: "DELETE_ORG_SUCCESS",
  DELETE_VEHICLE_TYPE_SUCCESS: "DELETE_VEHICLE_TYPE_SUCCESS",
  DELETE_AGENCY_TARIFF_PACKAGE_SUCCESS: "DELETE_AGENCY_TARIFF_PACKAGE_SUCCESS",
  DELETE_VEHICLE_CATEGORY_SUCCESS: "DELETE_VEHICLE_CATEGORY",
  DELETE_VEHICLEBRAND_SUCCESS: "DELETE_VEHICLEBRAND_SUCCESS",
  DELETE_AGENCY_VEHICLE_SUCCESS: "DELETE_AGENCY_VEHICLE_SUCCESS",
  DELETE_AGENCY_SUCCESS: "DELETE_AGENCY_SUCCESS",
  CREATE_AGENCY_VEHICLE_SUCCESS: "CREATE_AGENCY_VEHICLE_SUCCSS",
  CREATE_AGENCY_TARIFF_PACKAGE_SUCCESS: "CREATE_AGENCY_TARIFF_PACKAGE_SUCCSS",
  CREATE_ORGANIZATION_SUCCESS: "CREATE_ORGANIZATION_SUCCESS",

  FIND_ALL_ORGANIZATIONS: "FIND_ALL_ORGANIZATIONS",
  FIND_ORGANIZATION_SUCCESS: "FIND_ORGANIZATION_SUCCESS",

  FIND_ALL_ORGANIZATIONSBOOKING_SUCCESS:
    "FIND_ALL_ORGANIZATIONSBOOKING_SUCCESS",
  FIND_ALL_AGENCY_TARIFF_PACKAGES_SUCCESS:
    "FIND_ALL_AGENCY_TARIFF_PACKAGES_SUCCESS",
  AGENCY_NOT_SAVE: "AGENCY_NOT_SAVE",
  CREATE_AGENCY_VEHICLE: "CREATE_AGENCY_VEHICLE",
  CREATE_ORG_BOOKING_SUCCESS: "CREATE_ORG_BOOKING_SUCCESS",
  CREATE_CUSTOMER_QUOTATION_SUCCESS: "CREATE_CUSTOMER_QUOTATION_SUCCESS",
  FIND_ALL_CUSTOMER_QUOTATIONS: "FIND_ALL_CUSTOMER_QUOTATIONS",
  FIND_CUSTOMER_QUOTATION_SUCCESS: "FIND_CUSTOMER_QUOTATION_SUCCESS",

  DELETE_CUSTOMER_QUOTATION_SUCCESS: "DELETE_CUSTOMER_QUOTATION_SUCCESS",
  UPDATE_CUSTOMER_QUOTATION_SUCCESS: "UPDATE_CUSTOMER_QUOTATION_SUCCESS",
  CREATE_VEHICLE_CATEGORY_SUCCESS: "CREATE_VEHICLE_CATEGORY_SUCCESS",

  FIND_ALL_VEHCICLE_SUCCESS: "FIND_ALL_VEHCICLE_SUCCESS",
  FIND_ALL_VEHICLE_CATEGORY_SUCCESS: "FIND_ALL_VEHCICLE_CATEGORY_SUCCSS",

  UPDATE_VEHICLE_TYPE_SUCCESS: "UPDATE_VEHICLE_TYPE_SUCCESS",
  FIND_VEHICLE_CATEGORY_SUCCESS: "FIND_VEHICLE_CATEGORY_SUCCSS",

  ORG_BOOKING_UPDATE_SUCCESS: "ORG_BOOKING_UPDATE_SUCCESS",
  ORG_BOOKING_DELETE_SUCCESS: "ORG_BOOKING_DELETE_SUCCESS",

  SUCCESS: "SUCCESS",
  CREAE_SUBSCRIPTION_PLAN_SUCCESS: "CREAE_SUBSCRIPTION_PLAN_SUCCESS",

  SUBSCRIPTION_PLAN_UPDATE_SUCCESSFUL: "SUBSCRIPTION_PLAN_UPDATE_SUCCESSFUL",
  DELETE_SUBSCRIPTION_PLAN_SUCCESS: "DELETE_SUBSCRIPTION_PLAN_SUCCESS",
  FIND_SUBSCRIPTION_PLAN_SUCCESS: "FIND_SUBSCRIPTION_PLAN_SUCCESS",
  FIND_ALLVEHICLE_TYPE_SUCCESS: "FIND_ALLVEHICLE_TYPE_SUCCESS",
  FIND_ALL_VEHICLEBRAND_SUCCESS: "FIND_ALL_VEHICLEBRAND_SUCCESS",
  FIND_ALL_SUBSCRIPTION_SUCCESS: "FIND_ALL_SUBSCRIPTION_SUCCESS",
  FIND_SUCCESS: "FIND_SUCCESS",
  FIND_TARIFF_PACKAGE_SUCCESS: "FIND_TARIFF_PACKAGE_SUCCESS",

  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_MODULE_SUCCESS: "CREATE_MODULE_SUCCESS",

  ALREADY_EXISTENT: "ALREADY_EXISTENT",

  FIND_VEHICLE_TYPE_NAME_SUCCESS: "FIND_VEHICLE_TYPE_NAME_SUCCESS",
  FIND_VEHICLE_TYPE_SUCCESS: "FIND_VEHICLE_TYPE_SUCCESS",
  FIND_VEHICLEBRAND_SUCCESS: "FIND_VEHICLEBRAND_SUCCESS",
  FIND_ALL_AGENCY_VEHICLES_SUCCESS: "FIND_ALL_AGENCY_VEHICLES_SUCCESS",
  FIND_AGENCY_VEHICLES_SUCCESS: "FIND_AGENCY_VEHICLES_SUCCESS",
  FIND_AGENCY_VEHICLE_MODEL_SUCCESS: "FIND_AGENCY_VEHICLE_MODEL",
  CREATE_VEHICLES_Brand_SUCCESS: "CREATE_VEHICLES_BRAND_SUCCESS",

  USER_CREATE_ERROR: "USER_CREATE_ERROR",

  CREATE_VEHICLE_TYPE_SUCCESS: "CREATE_VEHICLE_SUCCESS",

  GET_USER_AND_ORG_SUCCESS: "GET_USER_AND_ORG_SUCCESS",

  ORG_LIST_DATA_SUCCESS: "ORG_LIST_DATA_SUCCESS",
  ORG_CREATED_SUCCESSFULLY: "ORG_CREATED_SUCCESSFULLY",
  OTP_SENT_SUCCESSFULLY: "OTP_SENT_SUCCESSFULLY",
};

export default globalMsg;
